package frc.robot.Sim;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import edu.wpi.first.hal.HAL;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.Auto.DynamicRouter;
import frc.robot.Sim.AIRobotSim.AIMode;
import frc.robot.Sim.AIRobotSim.CyclerPhase;
import frc.robot.Subsystems.Dashboard;

public class AIRobotSimTest {

    private AIRobotSim aiSim;

    @BeforeEach
    public void setup() {
        HAL.initialize(500, 0);
        aiSim = AIRobotSim.getInstance();
        aiSim.reset();
        DynamicRouter.clearObstacles();
    }

    @Test
    public void testAIModeEnumParsing() {
        assertEquals(AIMode.TACTICAL_DEFENSE, AIMode.fromString("TACTICAL_DEFENSE"));
        assertEquals(AIMode.LEAD_PURSUIT_INTERCEPT, AIMode.fromString("LEAD_PURSUIT_INTERCEPT"));
        assertEquals(AIMode.PINNING_BULLY, AIMode.fromString("PINNING_BULLY"));
        assertEquals(AIMode.AUTONOMOUS_CYCLER, AIMode.fromString("AUTONOMOUS_CYCLER"));
        assertEquals(AIMode.CHOREO_PATH, AIMode.fromString("CHOREO_PATH"));
        assertEquals(AIMode.MANUAL_2_PLAYER, AIMode.fromString("MANUAL_2_PLAYER"));

        // Fallback for null or unknown string
        assertEquals(AIMode.TACTICAL_DEFENSE, AIMode.fromString(null));
        assertEquals(AIMode.TACTICAL_DEFENSE, AIMode.fromString("INVALID_MODE"));
    }

    @Test
    public void testQueuingPositionsWhenDisabled() {
        SmartDashboard.putBoolean("Features/Opponent Robot", false);
        aiSim.simulationUpdate();

        Pose2d currentPose = aiSim.getDriveSimulation().getActualPoseInSimulationWorld();
        // Queuing position is off-field (Y < 0)
        assertTrue(currentPose.getY() < 0.0, "Disabled opponent robot should remain parked off-field");
    }

    @Test
    public void testCyclerInitialization() {
        assertEquals(CyclerPhase.HUNT_FUEL, aiSim.getCyclerPhase());
        assertEquals(0, aiSim.getAiScoreCount());
    }

    @Test
    public void testDynamicObstacleRegistrationWhenOnField() {
        // Position opponent robot on field in simulation
        aiSim.getDriveSimulation().setSimulationWorldPose(new Pose2d(5.0, 3.0, new Rotation2d()));
        SmartDashboard.putBoolean("Features/Opponent Robot", true);

        aiSim.update();

        // Should be registered in DynamicRouter
        assertEquals(1, DynamicRouter.getActiveObstacles().size(),
                "Active opponent on field should automatically register as a dynamic obstacle in DynamicRouter");
        assertEquals(5.0, DynamicRouter.getActiveObstacles().get(0).position.getX(), 0.1);
        assertEquals(3.0, DynamicRouter.getActiveObstacles().get(0).position.getY(), 0.1);
    }

    @Test
    public void testHubAvoidancePathGeneration() {
        Pose2d startPose = new Pose2d(14.0, 4.035, new Rotation2d());
        Pose2d targetPose = new Pose2d(8.27, 4.035, new Rotation2d());

        edu.wpi.first.math.kinematics.ChassisSpeeds speeds = aiSim.computeDriveToPoseSpeeds(startPose, targetPose, 3.5);
        assertNotNull(speeds);

        // Path generated by StaticPathfinder should contain at least one detour waypoint avoiding the Red Hub (11.94, 4.035)
        var path = aiSim.getCurrentPath();
        assertFalse(path.isEmpty(), "Path should not be empty");
        assertTrue(path.size() >= 2, "Path should contain at least one detour waypoint and final target");

        // The detour waypoint should divert in Y (away from 4.035) to clear the Hub
        Pose2d detour = path.get(0);
        assertTrue(Math.abs(detour.getY() - 4.035) > 1.0,
                "Detour waypoint must route around the Hub (Y diff > 1.0m, actual Y: " + detour.getY() + ")");
    }

    @Test
    public void testPlayerAvoidanceDeflection() {
        // Place AI bot at (10.0, 4.0) heading to (6.0, 4.0)
        Pose2d currentPose = new Pose2d(10.0, 4.0, new Rotation2d());
        Pose2d targetPose = new Pose2d(6.0, 4.0, new Rotation2d());

        // Player robot placed directly in front of AI bot at (9.0, 4.0)
        frc.robot.Subsystems.SwerveBase.getInstance().resetOdometry(new Pose2d(9.0, 4.0, new Rotation2d()));

        edu.wpi.first.math.kinematics.ChassisSpeeds speeds = aiSim.computeDriveToPoseSpeeds(currentPose, targetPose, 3.0);
        assertNotNull(speeds);

        // AI bot should be pushed back or deflected laterally away from player
        assertTrue(speeds.vxMetersPerSecond > -3.0 || Math.abs(speeds.vyMetersPerSecond) > 0.05,
                "AI bot should deflect or slow down to avoid player obstacle");
    }

    @Test
    public void testStallRecoveryWatchdog() throws Exception {
        Pose2d stuckPose = new Pose2d(12.0, 4.0, new Rotation2d());
        Pose2d targetPose = new Pose2d(8.0, 4.0, new Rotation2d());

        // Call computeDriveToPoseSpeeds multiple times with same stationary pose
        for (int i = 0; i < 25; i++) {
            aiSim.computeDriveToPoseSpeeds(stuckPose, targetPose, 3.0);
            Thread.sleep(20);
        }

        assertTrue(aiSim.isStalled(), "Watchdog should detect stall after being stationary under command for > 350ms");
    }
}
