package frc.robot.Intelligence;
import frc.robot.Intelligence.Archetype;
import frc.robot.Intelligence.State.WorldState;
import frc.robot.Intelligence.State.WorldStateBuilder;
import frc.robot.Intelligence.State.MatchScoreTracker;
import frc.robot.Intelligence.AIActionIntent;
import frc.robot.Intelligence.StrategicObjective;
import frc.robot.Intelligence.JevDecisionEngine;
import frc.robot.Intelligence.Sparring.AIRobotSim;
import frc.robot.Intelligence.Sparring.AIRobotInstance;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import frc.robot.Subsystems.Intake.IntakeState;
import frc.robot.Subsystems.Shooter.ShooterState;

/**
 * Concrete subsystem execution instructions generated by System 1 Tactical Reflex policy.
 */
public record AIActionIntent(
        StrategicObjective objective,
        Pose2d navigationTarget,
        Rotation2d aimOverride,       // Non-null if shooting / aiming at goal on the fly
        IntakeState intakeCommand,
        ShooterState shooterCommand,
        double targetFlywheelRPM,
        boolean triggerFeedKicker,
        double confidence,
        String rationale
) {}
