package frc.robot.Sim;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import frc.robot.Subsystems.Intake.IntakeState;
import frc.robot.Subsystems.Shooter.ShooterState;

/**
 * Concrete subsystem execution instructions generated by System 1 Tactical Reflex policy.
 */
public record AIActionIntent(
        StrategicObjective objective,
        Pose2d navigationTarget,
        Rotation2d aimOverride,       // Non-null if shooting / aiming at goal on the fly
        IntakeState intakeCommand,
        ShooterState shooterCommand,
        double targetFlywheelRPM,
        boolean triggerFeedKicker,
        double confidence,
        String rationale
) {}
